class Diagnostics:
    """
    Analyses residuals generated by the Digital Twin.

    Determines:
        - detected faults
        - machine health
        - machine status
    """

    def __init__(self):

        self.thresholds = {

            "rpm_error": 20.0,
            "current_error": 1.0,
            "temperature_error": 5.0,
            "voltage_error": 10.0,
            "frequency_error": 0.5,
            "torque_error": 3.0,
            "power_error": 0.5,
            "efficiency_error": 0.03,
        }

    def evaluate(self, residuals):

        faults = []

        if abs(residuals["rpm_error"]) > self.thresholds["rpm_error"]:
            faults.append("RPM deviation")

        if abs(residuals["current_error"]) > self.thresholds["current_error"]:
            faults.append("Current anomaly")

        if abs(residuals["temperature_error"]) > self.thresholds["temperature_error"]:
            faults.append("Cooling problem")

        if abs(residuals["voltage_error"]) > self.thresholds["voltage_error"]:
            faults.append("Voltage drop")

        if abs(residuals["frequency_error"]) > self.thresholds["frequency_error"]:
            faults.append("Frequency deviation")

        if abs(residuals["torque_error"]) > self.thresholds["torque_error"]:
            faults.append("Mechanical overload")

        if abs(residuals["power_error"]) > self.thresholds["power_error"]:
            faults.append("Power deviation")

        if abs(residuals["efficiency_error"]) > self.thresholds["efficiency_error"]:
            faults.append("Efficiency degradation")

        health = 100.0

        health -= abs(residuals["rpm_error"]) * 0.20
        health -= abs(residuals["current_error"]) * 2.0
        health -= abs(residuals["temperature_error"]) * 0.15
        health -= abs(residuals["voltage_error"]) * 0.10
        health -= abs(residuals["frequency_error"]) * 5.0
        health -= abs(residuals["torque_error"]) * 0.40
        health -= abs(residuals["power_error"]) * 2.0
        health -= abs(residuals["efficiency_error"]) * 100.0

        health = max(0.0, min(100.0, health))

        if health >= 95:
            status = "Healthy"
        elif health >= 80:
            status = "Warning"
        else:
            status = "Fault"

        return {
            "faults": faults,
            "health": health,
            "status": status,
        }